### ISSUE TITLE
Enhance ASCAT

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/Sarek#502] opened 2017-12-11 13:27 UTC
Add gc correction to ASCAT. 
Also, set gamma to 1 in ASCAT run.

**Comment by MaxUlysse** [comment] 2018-01-22 15:02
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance ASCAT](https://trello.com/c/7PLoQaSk/9-enhance-ascat)

**Comment by MaxUlysse** [comment] 2018-01-22 15:02
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance ASCAT](https://trello.com/c/7PLoQaSk/9-enhance-ascat)

**Comment by MaxUlysse** [comment] 2018-04-12 12:31
Duplicate of #407

**Closed by MaxUlysse** 2018-04-12 12:31 UTC
Labels: enhancement
