### ISSUE TITLE
Mix SIngle end and Paired end data

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#783] opened 2019-04-09 16:14 UTC
Hello, 
1) I have a sample sequenced both single end and paired end. SO I have 3 files for a sample. Can I use all of them?

2) Lets say I have 30 samples from 30 different patients. Can I run the Sarek pipeline ONCE LOCALLY and run the whole analysis for each sample? I do not wish to concatenate GVCFs

**Comment by MaxUlysse** [comment] 2019-04-11 09:39
Hi,

So for your first question, Sarek was designed for paired end files, but the bwa process could be modify to account for that. I'm afraid it's not something that we would encounter often, so I don't think it'll be very high in my list of priorities, but I can help you make a PR if you want.

For your second question, that is possible if you specify well your TSV file.
For example follow: https://github.com/SciLifeLab/Sarek-data/blob/master/testdata/tsv/tiny-multiple.tsv

**Comment by MaxUlysse** [comment] 2019-11-11 14:45
Closing due to moving to [nf-core/sarek](https://github.com/nf-core/sarek/).
If you still have the issue @kokyriakidis  can you please open a new one on the nf-core repo?
All the best,
Maxime

**Closed by MaxUlysse** 2019-11-11 14:45 UTC
Labels: enhancement, secondary
